name: Node.js CI

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - uses: actions/checkout@v2
      - run: node -v
      - run: ls -all
      - run: npm ci
      - run: npm test
