name: Node.js CI

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: echo This job does specify a container
      - run: node -v
      - run: ls -all
